version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: simonkabb/foodgram_web:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: simonkabb/foodgram_frontend:v2.0
    volumes:
      - result_build:/app/result_build/build
    depends_on:
      - db
